### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by vitorsome** [ilkkapeltola/visitdata#5]
Hey,

I've been using visitdatajs for a while and noticed that recently, when I updated the URL of the CDN (a simple include of the CDN in the header of my website), I'm getting the following error when I try to use a simple visitData.get().

![image](https://github.com/ilkkapeltola/visitdata/assets/97389137/d7e35485-d81a-43d4-b005-f44a7f01b116)

Could it maybe be a missing dependency in the project? Or perhaps I'm doing something wrong?
 
 Thanks in advance.

**Comment by ilkkapeltola** [comment]
Ah, yeah okay, I know why this is...

I'll fix it today.

**Comment by ilkkapeltola** [comment]
Fixed @vitorsome 
https://cdn.jsdelivr.net/npm/visitdata/dist/visitdata.umd.js

Please validate and if it works, close the issue, thank you 😊

**Comment by vitorsome** [comment]
Thank you so much!
